name: Deploy

on:
  push:
    branches:
      - master
jobs:
  setup_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set env variables from master branch
        id: set_env_master
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            echo "::set-output name=ENVIRONMENT::production"
          else
            echo "::set-output name=ENVIRONMENT::unknown"
          fi
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-latest

    needs: setup_job

    env:
      ENVIRONMENT: ${{ needs.setup_job.outputs.ENVIRONMENT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Setting .env variables for vite
        working-directory: ${{ github.workspace }}/client
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> $GITHUB_ENV

      - name: Creating .env for vite
        working-directory: ${{ github.workspace }}/client
        run: |
          touch .env
          echo VITE_API_URL="$VITE_API_URL" >> .env

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ github.workspace }}/client

      - name: Build project
        working-directory: ${{ github.workspace }}/client
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./client/dist

  deploy:
    name: Deploy
    needs: [setup_job, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: production-files
          path: ./client/dist

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
